### ISSUE TITLE
load model weights from server on start of task

### ISSUE THREAD

**Issue by martinjaggi** [epfml/FeAI#8]
and display a corresponding log message once it succeeded. only once this worked we should say the FL task is successfully joined

**Comment by martinjaggi** [comment]
can you link the PR?

**Comment by s314cy** [comment]
Sorry for closing this without explanation. As discussed in a previous Friday meeting, this feature is already fulfilled by the current code, i.e. tf.loadLayersModel fetches both the model.json and weights.bin files on server.
